version: '3.8'

services:
  loki:
    image: grafana/loki:2.9.4
    ports:
      - "3100:3100"
    volumes:
      - ./data/loki:/loki
      - ./config/loki/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:2.3.1
    ports:
      - "3200:3200"
      - "4317:4317"  # OTLP gRPC
    volumes:
      - ./data/tempo:/tmp/tempo

  mimir:
    image: grafana/mimir:2.11.0
    ports:
      - "9090:9090"  # Prometheus-compatible endpoint
    volumes:
      - ./data/mimir:/data
    command: -config.file=/etc/mimir/mimir.yaml

  grafana:
    image: grafana/grafana-enterprise:11.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./config/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=YourSecurePassword123!
      - GF_FEATURE_TOGGLES_ENABLE=tempoSearch tracesSampling
    depends_on:
      - loki
      - tempo
      - mimir
